export const treeRoots = [{
    name: 'Административное устройство',
    itemType: 'thematicSection',
    nodes: [{
        id: '1708ebd1-a8e4-4f55-97a4-c9f92c27f5ce',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:adm_centers_2015',
        type: 10,
        name: 'Административные центры поселений',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Административные центры поселений',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '148ac32a-21b1-4ba7-bc14-1b726abc0594',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:adm_centes_raioni',
        type: 10,
        name: 'Административные центры районов',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Административные центры районов',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'b01af452-d813-4256-9d4a-f6d81f172465',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:ADM_SUBJECT_2019',
        type: 10,
        name: 'Граница Ленинградской области_2019',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Граница Ленинградской области_2019',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '60de442c-9415-499f-870c-d8c29daef7f3',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Municipal_boundaries_2019_NEW',
        type: 10,
        name: 'Границы муниципальных районов и городского округа_2019',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Границы муниципальных районов и городского округа_2019',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '36bc1fc6-bde2-4b69-a333-057c8303ddda',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Rural_boundaries_2019_NEW',
        type: 10,
        name: 'Границы поселений_2019',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Границы поселений_2019',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '5ea23e1f-0ad7-457e-b794-a98a7df05c38',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Municipal_boundaries_2017_oktmo',
        type: 10,
        name: 'Муниципальные районы и городской округ (октмо)',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Муниципальные районы и городской округ (октмо)',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'ce4f3948-a91b-48fb-be9c-6704522dfb88',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Municipal_boundaries_2017_label_POINT',
        type: 10,
        name: 'Муниципальные районы и городской округ (подписи)',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Муниципальные районы и городской округ (подписи)',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'a7585f76-b3eb-42e6-a9d8-843837f19620',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:atd_np_settlement_polygon',
        type: 10,
        name: 'Населенные пункты',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Населенные пункты',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'c92f1953-4d0e-410e-872c-9e3f784a76c5',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Rural_boundaries_2019_label',
        type: 10,
        name: 'Подписи 2019',
        oktmo: 'Ленинградская область',
        thematicPart: 'Административное устройство',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Поселения 2019 (подписи)',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }]
}, {
    name: 'Адресная база',
    itemType: 'thematicSection',
    nodes: [{
        id: '3d8faf60-1b8a-497c-b002-5e63e71902f9',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:fpd_houses',
        type: 10,
        name: 'Адреса (дома)',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Адреса (дома)',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'a16d0424-f6e7-44f8-8648-6bc9183c7fa9',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:houses_volosovo',
        type: 10,
        name: 'Адреса(дома) Волосовского района',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Адреса(дома) Волосовского района',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '9ed2c7a1-f6f7-4882-850d-6578c6a47128',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:houses_kirovsk',
        type: 10,
        name: 'Адреса(дома) Кировского района',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Адреса(дома) Кировского района',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'a0b6577a-61bc-4bde-85a9-4d53771f9724',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:houses_priozersk',
        type: 10,
        name: 'Адреса(дома) Приозерского района',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Адреса(дома) Приозерского района',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '220332c4-a52b-42e5-b54a-beee2309cece',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:address_registry',
        type: 10,
        name: 'Адр. реестр ЛО',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Адресный реестр ЛО (сводный)',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '6b85b88b-aac0-46ff-a1e4-06049cc97ff5',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Boksitogorskiy_buildings',
        type: 10,
        name: 'Строения Бокситогорского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Бокситогорского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '44a24c16-ae69-42d7-ac69-7cd191a5454b',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:building_volosovo',
        type: 10,
        name: 'Строения Волосовского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Волосовского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'aa27a2a8-99b9-4f36-a6d6-71c516dc6c47',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Volhovskiy_buildings',
        type: 10,
        name: 'Строения  Волховского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Волховского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '945f7f04-6263-4e51-9c47-b198334f51e9',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Vsevologskiy_buildings',
        type: 10,
        name: 'Строения Всеволожского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Всеволожского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '9d862903-0597-4113-aecf-abb7fb8087ac',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Vyborgskiy_buildings',
        type: 10,
        name: 'Строения Выборгского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Выборгского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'fa29c992-9107-4403-8df8-45c20d5eb735',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Gatchinskiy_buildings',
        type: 10,
        name: 'Строения Гатчинского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Гатчинского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '472679f9-4851-4214-8836-12a05efcf7b2',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Kingisepskiy_buildings',
        type: 10,
        name: 'Строения Кингисепского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Кингисепского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '774db379-194f-4701-8035-3b7a7aa91bef',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Kirishskiy_buildings',
        type: 10,
        name: 'Строения Киришского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Киришского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'eb4d5ff4-4c17-40f3-8a2f-7932a4f176bc',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:building_kirovsk',
        type: 10,
        name: 'Строения Кировского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Кировского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '713fbff1-45b3-42ec-9e60-c509445b1195',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Lodeynopolnyy_buildings',
        type: 10,
        name: 'Строения Лодейнопольского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Лодейнопольского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '08099f24-9fb9-46b8-880b-6ba29a44ad70',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Lomonosovskiy_buildings',
        type: 10,
        name: 'Строения Ломоносовского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Ломоносовского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'e5734b0e-b64a-4a46-b40e-b9bc3c301672',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Luzhskiy_buildings',
        type: 10,
        name: 'Строения Лужского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Лужского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'a2b23a63-cff5-4a93-af47-e4a426804f9d',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Podporozhskiy_buildings',
        type: 10,
        name: 'Строения Подпорожского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Подпорожского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'ff39e6e4-55ed-4e9b-adce-372856a0fb70',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:building_priozersk',
        type: 10,
        name: 'Строения Приозерского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Приозерского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '9b0c6a35-5624-4c8e-ab24-107921c50923',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Slancevskiy_buildings',
        type: 10,
        name: 'Строения Сланцевского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Сланцевского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'c4cbee93-0827-4582-8449-83f4b672642f',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Sosnovoborskiy_buildings',
        type: 10,
        name: 'Строения Сосновоборский город. округ',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Сосновоборский город. округ',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: 'd4127bc1-684d-4abe-94db-ed60a663da4a',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Tihvinskiy_buildings',
        type: 10,
        name: 'Строения Тихвинского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Тихвинского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }, {
        id: '725db60f-18b2-49c5-9216-45ed3f5d5a12',
        url: 'http://gisfpd.petrosoft.su/geoserver/wms',
        layers: 'fpd:Tosnenskiy_buildings',
        type: 10,
        name: 'Строения Тосненского р-на',
        oktmo: 'Ленинградская область',
        thematicPart: 'Адресная база',
        serviceLogin: null,
        servicePassword: null,
        spatialCardName: 'Строения Тосненского р-на',
        style: {},
        isClustering: false,
        cqlFilter: null,
        itemType: 'layer',
        nodes: []
    }]
}]